"use client";

import posthog from "posthog-js";
import { PostHogProvider as PHProvider } from "posthog-js/react";
import { usePathname, useSearchParams } from "next/navigation";
import { useEffect, Suspense } from "react";

export function PostHogClient() {
  useEffect(() => {
    // Get distinct ID generated by our middleware if it exists
    let distinctId;
    try {
      const match = document.cookie.match(/(?:^|;)\s*ph_distinct_id=([^;]+)/);
      if (match) distinctId = match[1];
    } catch (e) {
      // Ignored
    }

    const initOptions: any = {
      api_host: process.env.NEXT_PUBLIC_POSTHOG_HOST,
      person_profiles: "identified_only",
      capture_pageview: false,
      capture_pageleave: true,
    };

    if (distinctId) {
      initOptions.bootstrap = {
        distinctID: distinctId,
      };
    }

    posthog.init(process.env.NEXT_PUBLIC_POSTHOG_KEY!, initOptions);
  }, []);

  return null;
}

export function PostPageView() {
  const pathname = usePathname();
  const searchParams = useSearchParams();

  useEffect(() => {
    if (pathname && posthog) {
      let url = window.origin + pathname;
      if (searchParams?.toString()) {
        url = url + `?${searchParams.toString()}`;
      }
      posthog.capture("$pageview", {
        $current_url: url,
      });
    }
  }, [pathname, searchParams]);

  return null;
}

export function PostHogProvider({ children }: { children: React.ReactNode }) {
  return (
    <PHProvider client={posthog}>
      <PostHogClient />
      <Suspense fallback={null}>
        <PostPageView />
      </Suspense>
      {children}
    </PHProvider>
  );
}
